/// progress_report.dart — Data model for aggregated progress statistics.
///
/// Generated by [ProgressProvider] from task, session, pomodoro,
/// and CGPA data. Contains task completion rates, weekly study
/// breakdown, subject-wise minutes, pomodoro statistics,
/// priority distribution, CGPA tracking, and daily averages.

class ProgressReport {
  // ── Task Statistics ──
  final int completedTasks;
  final int pendingTasks;
  final double completionRate;

  // ── Study Time Statistics ──
  final int totalStudyMinutes;
  final int todayMinutes;
  final int thisWeekMinutes;
  final double avgDailyMinutes;

  // ── Breakdown Maps ──
  final Map<String, int> weeklyStudyMinutes;
  final Map<String, int> subjectMinutes;

  // ── Pomodoro Statistics ──
  final int pomodoroCompleted;
  final int pomodoroTotal;
  final int totalFocusMinutes;

  // ── Task Priority Distribution ──
  final int highPriorityTasks;
  final int mediumPriorityTasks;
  final int lowPriorityTasks;

  // ── Overdue Tasks ──
  final int overdueTasks;

  // ── CGPA Tracking ──
  final double currentCgpa;
  final int totalSemesters;

  // ── Study Streak ──
  final int currentStreak;

  ProgressReport({
    required this.completedTasks,
    required this.pendingTasks,
    required this.totalStudyMinutes,
    required this.completionRate,
    required this.weeklyStudyMinutes,
    this.subjectMinutes = const {},
    this.todayMinutes = 0,
    this.thisWeekMinutes = 0,
    this.avgDailyMinutes = 0,
    this.pomodoroCompleted = 0,
    this.pomodoroTotal = 0,
    this.totalFocusMinutes = 0,
    this.highPriorityTasks = 0,
    this.mediumPriorityTasks = 0,
    this.lowPriorityTasks = 0,
    this.overdueTasks = 0,
    this.currentCgpa = 0,
    this.totalSemesters = 0,
    this.currentStreak = 0,
  });

  /// Pomodoro session completion rate as a percentage.
  double get pomodoroCompletionRate =>
      pomodoroTotal == 0 ? 0 : (pomodoroCompleted / pomodoroTotal) * 100;
}
